import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import type { User } from "../types/types";
import { selectAllUsers } from "../backend/utils";
import IssuerForm from "../components/IssuerForm";
import Navbar from "../components/Navbar";

export const getServerSideProps = async () => {
  const users = await selectAllUsers();
  return {
    props: {
      users,
    },
  };
};

const inter = Inter({ subsets: ["latin"] });

export default function Home({ users }: { users: User[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <Navbar />
        </div>
        <IssuerForm />
      </main>
    </>
  );
}
